//**@@@*@@@****************************************************
//
// Microsoft Windows
// Copyright (C) Microsoft Corporation. All rights reserved.
//
//**@@@*@@@****************************************************

//
// FileName:    CplExt.idl
//
// Abstract:    IDL source for CplExt.  This file will be processed by the
//              MIDL tool to produce the type library (CplExt.tlb) and
//              marshalling code.
//
// ----------------------------------------------------------------------------


import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(E6DB299B-B925-415A-879B-4A76D072F39A),
    dual,
    nonextensible,
    helpstring("IInterPropPage Interface"),
    pointer_default(unique)
]
interface IInterPropPage : IDispatch{
};


//[
//    object,
//    uuid(D379F7FB-66E0-427f-890D-1F479AD73B4B),
//    dual,
//    nonextensible,
//    helpstring("IAdvEndpointPropPage Interface"),
//    pointer_default(unique)
//]
//interface IAdvEndpointPropPage : IDispatch{
//};


[
    uuid(59390583-ED40-46D9-9B16-7800B9CC5CC2),
    version(1.0),
    helpstring("CplExt 1.0 Type Library")
]
library CplExtLib
{
    importlib("stdole2.tlb");
    
    // For Inter Property Page
    [
        uuid(A0AA1C9B-B09F-4AE4-90E0-77C8EDD977B2),
        helpstring("InterPropPage Class")
    ]
    coclass InterPropPage
    {
        [default] interface IInterPropPage;
    };

//    // For Advanced Endpoint Property Page
//    [
//        uuid(6C57B2A2-91F5-4b90-93D5-FAB82485ECA6),
//        helpstring("AdvEndpointPropPage Class")
//    ]
//    coclass AdvEndpointPropPage
//    {
//        [default] interface IAdvEndpointPropPage;
//    };
};
