//
// InterAPOInterface.idl -- Copyright (c) Microsoft Corporation. All rights reserved.
//
// Description:
//
//      The interface and type definitions for Inter APO functionality.
//
import "oaidl.idl";
import "ocidl.idl";
import "audioenginebaseapo.idl";

[
    object,
    uuid(700118CA-F9FC-4C04-BF7A-49B549F7F0E7),
    pointer_default(unique)
]
interface IInterAPOMFX : IUnknown
{
};

[
    object,
    uuid(80CD02D2-8A3F-4250-9E47-A6795020AC79),
    pointer_default(unique)
]
interface IInterAPOSFX : IUnknown
{
};

